#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config{/log/rtorrent,/log/rutorrent,/rtorrent/rtorrent_sess,/rutorrent/settings/users} \
	/config/rutorrent/profiles{/settings,/torrents,/users,/tmp} \
	/downloads{/complete,/download,/watch} \
	/downloads/watch{/book,/game,/movie/radarr,/movie/radarr-swedish,/music,/other,/software,/tv/sonarr,/tv/sonarr-swedish} \
	/downloads/download{/book,/game,/movie/radarr,/movie/radarr-swedish,/music,/other,/software,/tv/sonarr,/tv/sonarr-swedish} \
	/downloads/complete{/book,/game,/movie/radarr,/movie/radarr-swedish,/music,/other,/software,/tv/sonarr,/tv/sonarr-swedish} \
	/run/php

cd /defaults/rutorrent-conf || exit
shopt -s globstar nullglob
for i in *
do
	[[ ! -e "/config/rutorrent/settings/${i}" ]] && cp -v "${i}" "/config/rutorrent/settings/${i}"
done

[[ ! -e /config/rtorrent/rtorrent.rc ]] && \
	cp /defaults/rtorrent.rc /config/rtorrent/rtorrent.rc
cp -pr /config/rutorrent/settings/* /app/rutorrent/conf/

# copy over any theme files to themes folder
[[ -e /config/themes ]] && \
	cp -R /config/themes/ /app/rutorrent/plugins/theme/

# copy over any plugins to the plugins folder
[[ -e /config/plugins ]] && \
	cp -R /config/plugins/ /app/rutorrent/

# delete lock file if exists
[[ -e /config/rtorrent/rtorrent_sess/rtorrent.lock ]] && \
	rm /config/rtorrent/rtorrent_sess/rtorrent.lock

# permissions
chown 1000:1000 \
	/downloads \
	/downloads{/complete,/download,/watch} \
	/downloads/watch{/book,/game,/movie/radarr,/movie/radarr-swedish,/music,/other,/software,/tv/sonarr,/tv/sonarr-swedish} \
	/downloads/complete{/book,/game,/movie/radarr,/movie/radarr-swedish,/music,/other,/software,/tv/sonarr,/tv/sonarr-swedish} \
	/downloads/download{/book,/game,/movie/radarr,/movie/radarr-swedish,/music,/other,/software,/tv/sonarr,/tv/sonarr-swedish}

chown -R 1000:1000 \
	/config \
	/run \
	/app/rutorrent

chmod -R 755 /config/rutorrent/profiles
